export { default as Scholar } from "./Scholar";
export { default as Github } from "./Github";
export { default as Linkedin } from "./Linkedin";
export { default as Medium } from "./Medium";
export { default as Twitter } from "./Twitter";
export { default as Link } from "./Link";
export { default as Live } from "./Live";
export { default as Slides } from "./Slides";
export { default as YouTube } from "./YouTube";
